version: 3
endpoint: "https://mutual-flea-53.hasura.app"
admin_secret: "35gEAdwe2Hj4lGPyTAMavTfwhu6MiY4tU7xbrEVxikSdRkiWZrYn7UEQ6JKDP1Ga"
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
